"""add posting starting and finishing timestamps for events

Revision ID: c0c81a72823d
Revises: aa6d6c221f00
Create Date: 2025-12-20 15:09:26.527771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c81a72823d'
down_revision: Union[str, Sequence[str], None] = 'aa6d6c221f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'finished_at')
    op.drop_column('events', 'started_at')
    op.drop_column('events', 'published_at')
    # ### end Alembic commands ###
